### ISSUE TITLE
Error - "Missing credentials in config"

### ISSUE THREAD

**Issue by sachamicrosoft** [nodef/extra-amazontranslate#1]
Wolfram--

I'm trying to run this but get a "Missing credentials in config". Text cmdline is simply

amazontranslate "hi" -ot "jp" -l

No logs - the program just hangs. Ideas?

--Sam

**Comment by wolfram77** [comment]
Hello @sachamicrosoft indeed credentials are missing!
You need to provide "access key" and "secrect access key" either as:
- command line parameters, or
- environment variables, or as
- credentials file.


Just copying from https://www.npmjs.com/package/extra-awsconfig:
```bash
# Environment variables: 
$AWS_ACCESS_KEY_ID           # set your default AWS access key ID 
$AWS_SECRET_ACCESS_KEY       # set your default AWS secret access key 
$AWS_DEFAULT_REGION          # set default region to send service requests to (us-east-1) 
$AWS_PROFILE                 # set default AWS config profile to use (default) 
$AWS_SHARED_CREDENTIALS_FILE # set default AWS credentails file path (~/.aws/credentials) 
$AWS_CONFIG_FILE             # set default AWS config file path (~/.aws/config) 
 
# Credential/Config file (INI): 
[default]
aws_access_key_id = ...
aws_secret_access_key = ...
region = us-east-1
...
 
# Credential/Config file (JSON, default profile): 
{
  "accessKeyId": "...",
  "secretAccessKey": "...",
  "region": "us-east-1",
  ...
}
```

Reference: https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html

**Comment by sachamicrosoft** [comment]
Thanks so as long as I set $AWS_ACCESS_KEY_ID = <my Secret here> and $AWS_SECRET_ACCESS_KEY = <my other Secret here> in the CLI shell and then run amazontranslate "hi" -ot "jp" -l again it should work?

**Comment by wolfram77** [comment]
I think so. I have not tried Japanese.
